FrontEndHost: https://crc.castimaging.fr
Routes:
  enable: true
  tls: true
CreateStorageClass: true
DiskClassName: crc-csi-hostpath-provisioner-delete
FileClassName: crc-csi-hostpath-provisioner-delete
SharedVolumeAccessMode: ReadWriteOnce
McpServer:
  enable: true
ExtendProxy:
  enable: true
  exthostname: crc-extend.castimaging.fr
ImagingLicense: "CAST R&D:3;EFP,P1,P2,P3,P4:20260630:WKWKUZUR"
EnforceBalancedAffinity: false
size_castdir: 10Gi
size_shared_datadir: 10Gi
size_db_data: 10Gi
size_neo4jdata: 10Gi
CastStorageService:
  ssl: true
