{{- if .Values.UseImagePullSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.Base64EncodedDockerconfigjson }}
kind: Secret
metadata:
  name: imagepull-sec
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- end }}
---
# Create the default secret ONLY if no external secret is provided in the values
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: imaging-pwd-sec
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgres-db-password: {{ .Values.PostgresDbPassword | default "cG9zdGdyZXM=" }}
  operator-db-password: {{ .Values.OperatorDbPassword | default "Q2FzdEFJUA==" }}
  guest-db-password: {{ .Values.GuestDbPassword | default "V2VsY29tZVRvQUlQ" }}
  keycloak-db-password: {{ .Values.KeycloakDbPassword | default "a2V5Y2xvYWs=" }}
  keycloak-admin-password: {{ .Values.KeycloakAdminPassword | default "YWRtaW4=" }}
  neo4j-password: {{ .Values.Neo4jPassword | default "aW1hZ2luZw==" }}
  operator-db-password-crypted2: {{ .Values.OperatorDbPasswordCrypted2 | b64enc }}
  {{- if .Values.SMTP.enable }}
  smtp-password: {{ .Values.SMTP.SPRING_MAIL_PASSWORD | default "bXktc210cC1wYXNzd29yZA==" }}
  {{- end }}
{{- end }}